# fly.toml file generated for job-descriptions on 2023-03-12T18:14:44Z

app = "job-descriptions"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  [build.args]
    NEXT_PUBLIC_GPT_MODEL = "gpt-4"

[env]
  PORT = "8080"

[experimental]
  enable_consul = true
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

# [mounts]
#   source = "localdata"
#   destination = "/var/lib/litefs"

[deploy]
  release_command = "npx prisma db push"