name: Deploy to Fly.io
on:
  push:
    branches:
      - production
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          NEXT_PUBLIC_GPT_MODEL: ${{ secrets.NEXT_PUBLIC_GPT_MODEL }}
