name: Deploy to Fly.io
on:
  push:
    branches:
      - production
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Get Current Date and Time of Build
        id: set_date_and_time
        run: echo "build_time=$(date +'%Y-%m-%d %H:%M:%S %Z')" >> $GITHUB_ENV
      - name: Debug Build Time
        run: echo ${{ env.build_time }}
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          NEXT_PUBLIC_GPT_MODEL: ${{ secrets.NEXT_PUBLIC_GPT_MODEL }}
          NEXT_PUBLIC_APP_VERSION: ${{ github.ref_name }}-${{ env.build_time }}
